name: Get S3 Bucket Size

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  get-s3-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ROLE_ARN }} # Use the secret for the role ARN
          aws-region: us-east-1 # Replace with your bucket's region
          role-session-name: GitHubActionsSession

      - name: Get S3 Bucket Size
        run: |
          echo "Listing objects in bucket:"
          aws s3 ls s3://${{ secrets.AWS_S3_BUCKET_NAME }} --recursive --human-readable --summarize
